openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:9000'
tags:
  - name: quotation
paths:
  '/rfq/{rfqNumber}/quotation':
    put:
      parameters:
        - schema:
            type: string
          example: RFQ1
          name: rfqNumber
          in: path
          required: true
      tags:
        - quotation
      operationId: updateQuotation
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quotation'
            example:
              pricedItems:
                - title: Electric cables installation
                  description: Installation of cables
                  price: 410
                - title: Light points check
                  description: Checking Light points
                  price: 80
                - title: Electric flow test
                  description: Electric flow test
                  price: 827
components:
  schemas:
    Quotation:
      title: Quotation
      type: object
      properties:
        pricedItems:
          type: array
          items:
            $ref: '#/components/schemas/QuotationPricedItem'
        status:
          type: string
          enum:
            - READY
            - CANCELLED
      required:
        - status
    QuotationPricedItem:
      title: QuotationPricedItem
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
      required:
        - title
        - price